// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package io.grpc.testing.integration;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\014grpc.testing\032\013empty.proto\032" +
      "\016messages.proto2\313\005\n\013TestService\0225\n\tEmpty" +
      "Call\022\023.grpc.testing.Empty\032\023.grpc.testing" +
      ".Empty\022F\n\tUnaryCall\022\033.grpc.testing.Simpl" +
      "eRequest\032\034.grpc.testing.SimpleResponse\022O" +
      "\n\022CacheableUnaryCall\022\033.grpc.testing.Simp" +
      "leRequest\032\034.grpc.testing.SimpleResponse\022" +
      "l\n\023StreamingOutputCall\022(.grpc.testing.St" +
      "reamingOutputCallRequest\032).grpc.testing." +
      "StreamingOutputCallResponse0\001\022i\n\022Streami" +
      "ngInputCall\022\'.grpc.testing.StreamingInpu" +
      "tCallRequest\032(.grpc.testing.StreamingInp" +
      "utCallResponse(\001\022i\n\016FullDuplexCall\022(.grp" +
      "c.testing.StreamingOutputCallRequest\032).g" +
      "rpc.testing.StreamingOutputCallResponse(" +
      "\0010\001\022i\n\016HalfDuplexCall\022(.grpc.testing.Str" +
      "eamingOutputCallRequest\032).grpc.testing.S" +
      "treamingOutputCallResponse(\0010\001\022=\n\021Unimpl" +
      "ementedCall\022\023.grpc.testing.Empty\032\023.grpc." +
      "testing.Empty2U\n\024UnimplementedService\022=\n" +
      "\021UnimplementedCall\022\023.grpc.testing.Empty\032" +
      "\023.grpc.testing.Empty2\177\n\020ReconnectService" +
      "\0221\n\005Start\022\023.grpc.testing.Empty\032\023.grpc.te" +
      "sting.Empty\0228\n\004Stop\022\023.grpc.testing.Empty" +
      "\032\033.grpc.testing.ReconnectInfo2\206\002\n\030LoadBa" +
      "lancerStatsService\022c\n\016GetClientStats\022&.g" +
      "rpc.testing.LoadBalancerStatsRequest\032\'.g" +
      "rpc.testing.LoadBalancerStatsResponse\"\000\022" +
      "\204\001\n\031GetClientAccumulatedStats\0221.grpc.tes" +
      "ting.LoadBalancerAccumulatedStatsRequest" +
      "\0322.grpc.testing.LoadBalancerAccumulatedS" +
      "tatsResponse\"\0002\213\001\n\026XdsUpdateHealthServic" +
      "e\0226\n\nSetServing\022\023.grpc.testing.Empty\032\023.g" +
      "rpc.testing.Empty\0229\n\rSetNotServing\022\023.grp" +
      "c.testing.Empty\032\023.grpc.testing.Empty2{\n\037" +
      "XdsUpdateClientConfigureService\022X\n\tConfi" +
      "gure\022$.grpc.testing.ClientConfigureReque" +
      "st\032%.grpc.testing.ClientConfigureRespons" +
      "eB\035\n\033io.grpc.testing.integrationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.grpc.testing.integration.EmptyProtos.getDescriptor(),
          io.grpc.testing.integration.Messages.getDescriptor(),
        });
    io.grpc.testing.integration.EmptyProtos.getDescriptor();
    io.grpc.testing.integration.Messages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
