// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simpleservice.proto

package io.grpc.testing.protobuf;

public interface SimpleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.testing.SimpleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An optional string message for test.
   * </pre>
   *
   * <code>string requestMessage = 1;</code>
   * @return The requestMessage.
   */
  java.lang.String getRequestMessage();
  /**
   * <pre>
   * An optional string message for test.
   * </pre>
   *
   * <code>string requestMessage = 1;</code>
   * @return The bytes for requestMessage.
   */
  com.google.protobuf.ByteString
      getRequestMessageBytes();
}
